#!/bin/bash 

# set variables
first_arg=$1

main() {
    
    log_name=$2 
    
    log-checker

    if [ $# -gt 1 ]; then
        # check the first argument and decide what to do
        case $first_arg in 
            "list-ip")
            
            list-ip    
            
            ;;
            "list-hosts")
            
            list-hosts

            ;;

            "list-uri")
            
            list-uri
            
            ;;
            "hist-ip")
        
            hist-ip
            
            ;;    
        esac
    else 

        log_name=$1
        # print the inside of the log 
        cat "$log_name"

    fi
    
}

log-checker() {

    # Checks if the file contains something
    if [[ ! -f "$log_name" ]]; then
        echo "Error, log does not exist" ;
        return 1 
    # Checks if the file is not empty
    elif [[ ! -s "$log_name" ]]; then
        echo "Error, $log_name is empty";
        return 1 
    fi
    return 0
}

list-ip() {
    
    # Print list of the first column that contains IP addresses
    awk '{print $1}' "$log_name"
}

list-hosts() {

    # Make list of IP address that are piped into loop
    awk '{print $1}' "$log_name" | while read ip; do
    # For each IP address is made DNS lookup
    host $ip | awk '{print $NF}'
    done 

}

list-uri() {
    
    # filter all lines without HTTP/1.1 then prints list of uri-
    grep "HTTP/1.1" "$log_name" | awk '{print $7}' 

}

hist-ip() {

    # sort all IP addresses by the appearence 
    awk '{print $1}' "$log_name" | sort | uniq -c | sort -r -k1,1 |
    awk '{
    
        printf "%s (%d): ", $2, $1
    
        for(i = 0; i < $1; i++){
        
            printf "#"
        }

        printf "\n"
    }'

}

main "$@"