#!/bin/bash 

# set variables
first_arg=$1

main() {
    # check the first argument and decide what to do
    case $first_arg in 
        "list-ip")
        shift 1
        
        log_name=$1 
        
        list-ip    
        ;;
        "list-hosts")
        shift 1

        log_name=$1

        list-host

        ;;

        "list-uri")
        shift 1 

        log_name=$1

        list-uri
        ;;
    esac
    
}

log-checker() {

    if [[ ! -f "$log_name" ]]; then
        echo "Error, log does not exist" ;
        return 1 
    elif [[ ! -s "$log_name" ]]; then
        echo "Error, $log_name is empty";
        return 1 
    fi
    return 0
}

list-ip() {
    
    log-checker || return 1
    
    awk -F"- -" '{print $1}' "$log_name"
}

list-hosts() {

    log-checker || return 1
    
    awk -F"- -" '{print $1}' "$log_name" | while read ip; do
    # $NF is the same as writing the last column number
    host $ip | awk '{print $NF}'
    done 

}

list-uri() {
    
    log-checker || return 1

    grep "HTTP/1.1" "$log_name" | awk '{print $7}' 

}

main "$@"