#!/bin/bash 

main() {

    #set variables
    command_name=""
    time_after=""
    time_before=""
    main_ip=""
    main_uri=""
    file_name="${@: -1}"
    
    # loop all arguments
    while [ $# -gt 0 ]; do
        # check the first argument and decide what to do
        case $1 in 
            "-a")

            time_after=$2
            shift 2
            
            ;;
            "-b")
            
            time_before=$2
            shift 2
            
            ;;
            "-ip")
            
            main_ip=$2
            shift 2
            
            ;;
            "-uri")
            
            main_uri=$2
            shift 2 

            ;;
            "list-ip"|"list-hosts"|"list-uri"|"hist-ip"|"hist-load")
            
            # if find one of the command save it and break loop
            command_name="$1"
            shift
            
            break
            ;;
            *)

            break 
            ;;
        esac
    done

    # Checks if the file exist 
    log-checker "$@" || return 1

    #  Go on if one of the filters or command is not empty
    if [[ -n "$command_name" || -n "$time_after" || -n "$time_before" || -n "$main_ip" || -n "$main_uri" ]]; then 
        # read the file, launch filter function and then launch command function
        gzip -dcf "$@" 2>/dev/null | 
        date-filter "$time_after" "$time_before"| ip-filter "$main_ip" | uri-filter "$main_uri" | 
        if [[ -n "$command_name" ]]; then 
            command-apply 
        else 
        # if no command is read print the content of the file
            cat 
        fi  
    else 
        # read file name from stdin 
        gzip -dc "$@" 2>/dev/null

    fi
}

log-checker() {
    
    for file_name in "$@"; do
        # Checks if the file exist
        if [[ ! -f "$file_name" ]]; then
            echo "Error, $file_name does not exist" >&2
            return 1 
        # Checks if the file is not empty
        elif [[ ! -s "$file_name" ]]; then
            echo "Error, $file_name is empty" >&2
            return 1 
        fi
    done
    return 0
}

date-filter() { 

    local formatted_after=""
    local formatted_before=""

    # delete all dashes and colon from the users dates after and before
    if [[ -n "$time_after" ]]; then
        local formatted_after=$(echo "$time_after" | tr -d " :- ")
    fi
    
    if [[ -n "$time_before" ]]; then
        local formatted_before=$(echo "$time_before" | tr -d " :- ")
    fi

    # BEGIN is making dictionary of numbers for each month
    # define varibles for time after and before
    # Clear the [ before the date
    # split the log date to array d 
    # compare date from log with the time from argument   
    awk -v after="$formatted_after" -v before="$formatted_before" '
    BEGIN {
       
        m["Jan"]="01"; m["Feb"]="02"; m["Mar"]="03"; m["Apr"]="04"; m["May"]="05"; m["Jun"]="06";
        m["Jul"]="07"; m["Aug"]="08"; m["Sep"]="09"; m["Oct"]="10"; m["Nov"]="11"; m["Dec"]="12"
    
    }
    {
        cleared_date = substr($4, 2)
    
        split(cleared_date, d, /[\/:]/)

        log_date = d[3] m[d[2]] d[1] d[4] d[5] d[6]

        

        if (after != "" && log_date <= after) {
        
            next 

        }
        if (before != "" && log_date >= before) {
        
            exit 
        
        }
        
        print $0        
    }'
}

# print only ip address added for the filter
ip-filter() {
    
    local main_ip=$1
    
    if [[ -n "$main_ip" ]]; then 
        # comparing each ip address with needed ip address
        awk -v ip="$main_ip" '$1 == ip { print $0 }'
    
    else 
        cat
    fi
}


uri-filter() {

    local main_uri=$1

    if [[ -n "$main_uri" ]]; then

        awk -v uri="$main_uri" '$7 ~ uri { print $0 }'
    
    else 
        cat    
    fi
}

# apply command using saved command name
command-apply() {

    case "$command_name" in 
        "list-ip")      list-ip  ;;
        "list-hosts")   list-hosts ;;
        "list-uri")     list-uri ;;
        "hist-ip")      hist-ip ;;
        "hist-load")    hist-load;;
    esac
}

list-ip() {
    
    # Print list of the first column that contains IP addresses
    awk '{print $1}' "$@" | sort -u
}

list-hosts() {

    # Make list of IP address that are piped into loop
    awk '{print $1}' "$@" | while read ip; do
    # For each IP address is made DNS lookup
    # If it cant find the domain name it will print IP address
    host "$ip"| awk -v ip="$ip" '
        /NXDOMAIN/ {
            print ip; exit
        }
        /domain name/ {
            print $NF; exit
        }
    ' 
    
    done 

}

list-uri() {
    
    # filter all lines without HTTP/1.1 then prints list of uri-
    grep "HTTP/1.1" "$@" | awk '{print $7}' | sort -u

}

hist-ip() {

    # sort all IP addresses by the appearence 
    awk '{print $1}' "$@" | sort | uniq -c | sort -r -k1,1 |
    awk '{
    
        printf "%s (%d): ", $2, $1
    
        for(i = 0; i < $1; i++){
        
            printf "#"
        }

        printf "\n"
    }'

}

hist-load() {

    # take time from the log
    awk '
    BEGIN {
       
        m["Jan"]="01"; m["Feb"]="02"; m["Mar"]="03"; m["Apr"]="04"; m["May"]="05"; m["Jun"]="06";
        m["Jul"]="07"; m["Aug"]="08"; m["Sep"]="09"; m["Oct"]="10"; m["Nov"]="11"; m["Dec"]="12"
    
    }
    {

    cleared_date = substr($4, 2)
    
    split(cleared_date, d, /[\/:]/)

    printf "%s-%s-%s %s:00\n", d[3], m[d[2]], d[1], d[4]

    }
    ' | sort | uniq -c | 
    # do the same thing like in hist ip 
    awk '{
    
        printf "%s %s (%d): ", $2, $3, $1

        for(i = 0; i < $1; i++){
        
            printf "#"
        
        }
    
        printf "\n"
    }'
}

main "$@"